server:
  port: 9000

spring:
  application:
    name:
      API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/users/auth/**
        - id: CANDIDATE-INFORMATION
          uri: lb://CANDIDATE-INFORMATION
          predicates:
            - Path=/api/v1/candidates/**
        - id: ADVERSE-ACTION
          uri: lb://ADVERSE-ACTION
          predicates:
            - Path=/api/v1/adverseactions/**
        - id: COURT-SEARCH
          uri: lb://COURT-SEARCH
          predicates:
            - Path=/courtSearches/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost