server:
  port: 9001

spring:
  application:
    name: CANDIDATE-INFORMATION
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://18.215.255.254 :30002/checker119?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
frontendlocal:
  url: http://localhost:8080/